version: '3.1'
services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./sites-enabled:/etc/nginx/sites-enabled:ro
          - /home/svendcs/projects/judoassistant.com/html:/var/www/judoassistant.com/html:ro
          - certbot-etc:/etc/letsencrypt
          - certbot-var:/var/lib/letsencrypt
          - web-root:/var/www/html
        ports:
          - "80:80"
    cerbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - web-root:/var/www/html
      command: certonly --webroot --webroot-path=/var/www/html --email svendcs@svendcs.com --agree-tos --no-eff-email --staging -d judoassistant.com  -d www.judoassistant.com
volumes:
    db:
    tournaments:
    certbot-etc:
    certbot-var:
    web-root:

