version: '3.1'
services:
    nginx:
        image: nginx
        container_name: judoassistant-nginx
        restart: unless-stopped
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./sites-enabled:/etc/nginx/sites-enabled:ro
          - /var/www/judoassistant.com/html:/var/www/judoassistant.com/html:ro
          - /etc/letsencrypt:/etc/letsencrypt
        ports:
          - "80:80"
          - "443:443"
    web-frontend:
      image: judoassistant/judoassistant-web-frontend:latest
      container_name: judoassistant-web-frontend

volumes:
    db:
    tournaments:

